# SPDX-FileCopyrightText: 2024 shadPS4 Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later

name: Steam Deck Qt Build

on: 
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'push' }}

env:
  BUILD_TYPE: Release

jobs:
  get-info:
    runs-on: ubuntu-24.04
    outputs:
      date: ${{ steps.vars.outputs.date }}
      shorthash: ${{ steps.vars.outputs.shorthash }}
    steps:
    - uses: actions/checkout@v5
    - name: Get date and git hash
      id: vars
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "shorthash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  linux-qt-deck:
    runs-on: ubuntu-24.04
    needs: get-info
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Add LLVM repository
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble-19 main'

    - name: Install dependencies
      run: sudo apt-get update && sudo apt install -y libx11-dev libxext-dev libwayland-dev libdecor-0-dev libxkbcommon-dev libglfw3-dev libgles2-mesa-dev libfuse2 clang-19 mold build-essential qt6-base-dev qt6-tools-dev qt6-multimedia-dev libasound2-dev libpulse-dev libopenal-dev libudev-dev libxcursor-dev libxi-dev libxss-dev libxtst-dev

    - name: Cache CMake Configuration
      uses: actions/cache@v4 
      env: 
          cache-name: ${{ runner.os }}-qt-cache-cmake-configuration
      with: 
          path: |  
            ${{github.workspace}}/build 
          key: ${{ env.cache-name }}-${{ hashFiles('/CMakeLists.txt', 'cmake/') }} 
          restore-keys: | 
            ${{ env.cache-name }}- 

    - name: Cache CMake Build
      uses: hendrikmuhs/ccache-action@v1.2.19
      env:
          cache-name: ${{ runner.os }}-qt-cache-cmake-build
      with:
        append-timestamp: false
        key: ${{ env.cache-name }}-${{ hashFiles('/CMakeLists.txt', 'cmake/') }}

    - name: Configure CMake

      run: |
        cmake --fresh -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DCMAKE_C_COMPILER=clang-19 \
          -DCMAKE_CXX_COMPILER=clang++-19 \
          -DCMAKE_CXX_FLAGS="-march=znver2 -O3 -flto=thin -mtune=znver2 -ffast-math -DNDEBUG -ffunction-sections -fdata-sections" \
          -DCMAKE_C_FLAGS="-march=znver2 -O3 -flto=thin -mtune=znver2 -ffast-math -DNDEBUG -ffunction-sections -fdata-sections" \
          -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=mold -Wl,--gc-sections" \
          -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=mold -Wl,--gc-sections" \
          -DENABLE_QT_GUI=ON \
          -DENABLE_UPDATER=ON \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(nproc)

    - name: Run AppImage packaging script
      run:  ./.github/linux-appimage-qt.sh

    - name: Rename AppImage for Clarity
      run: |
        mv Shadps4-qt.AppImage shadps4-steamdeck-qt-${{ needs.get-info.outputs.date }}-${{ needs.get-info.outputs.shorthash }}.AppImage

    - uses: actions/upload-artifact@v4
      with:
        name: shadps4-steamdeck-qt-${{ needs.get-info.outputs.date }}-${{ needs.get-info.outputs.shorthash }}
        path: shadps4-steamdeck-qt-${{ needs.get-info.outputs.date }}-${{ needs.get-info.outputs.shorthash }}.AppImage
